# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
os: osx
osx_image: xcode10.2

-before_install:
 - |
    gem install xcpretty slather -N
 
script:
- |
    set -o pipefail
    xcodebuild clean test -workspace Example/Mockit.xcworkspace -scheme Mockit_Tests -destination "platform=iOS Simulator,name=iPhone 6 Plus" ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test | xcpretty -c

after_success: slather
